### ISSUE TITLE
[Aktivitäten ansehen] Detailansicht implementieren

### ISSUE THREAD

**Issue by snowfoxD** [sweIhm/sweiproject-tg1b-2#3]
Als Interessierter will ich Aktivitäten im Detail ansehen, damit ich mich darüber informieren kann. Dazu sollen alle verfügbaren Informationen über eine Aktivität (außer E-Mail Adresse) auf einer eigenen Seite angezeigt werden.

# Akzeptanzkriterien:
- Aktivitäten werden anonym angezeigt
- Aktivitätendetaills werden alle angezeigt

**Comment by v4lli** [comment]
Die Kategorie wird noch nicht in der Detailansicht angezeigt :(
