### ISSUE TITLE
[Aktivität anlegen] E-Mail verifizieren

### ISSUE THREAD

**Issue by snowfoxD** [sweIhm/sweiproject-tg1b-2#4]
Als Teilnehmer will ich meine Email verifizieren, damit ich eine Aktivität anlegen kann. Dazu gebe ich zunächst auf einem öffentlich zugänglichem Formular meine E-Mail-Adresse als einzigen Wert ein. Die Adresse muss auf ihre Endung geprüft werden, wenn die Endung passt wird ein geheimer Anlege-Link generiert und an die Adresse versendet.

# Akzeptanzkriterien:
- Email wird nur akzeptiert, wenn sie auf @hm.edu oder @calpoly.edu endet.
- Link wird per Email zugestellt.
- Link führt zu Anlegeformular.

**Comment by v4lli** [comment]
Fertig
