### ISSUE TITLE
[Aktivitäten visualisieren] Graphische Visualisierung implementieren

### ISSUE THREAD

**Issue by v4lli** [sweIhm/sweiproject-tg1b-2#9]
Als Interessierter möchte ich eine Übersicht über alle Aktivitäten visualisiert bekommen, damit ich schneller einen Überblick über Aktivitäten bekomme. Dazu soll ein Histogramm implementiert werden, welches die Aktivitäten entsprechend den aktuellen Filterkriterien visualisiert. Daher ist eine Einbindung in die [Aktivität filtern]-Funktion notwendig.

# Akzeptanzkriterien
- Mindestens eine Art von Visualisierung
- Visualisierte Daten sind an Filterkriterien gebunden
- Verknüpfung zwischen Visualisierung und Detailansicht(en)

**Comment by EkaterinaKasina** [comment]
Aktivitäten können nun auf zwei Arten visualisiert werden:
1. sortiert nach Fakultäten
2. sortiert nach Kategorien
